### ISSUE TITLE
Small bug with Generic theme?

### ISSUE THREAD

**Issue by woovter** [vintagedaddyo/MyBB_Plugin-MyFontAwesomeIcons#2]
Great plugin, makes everything easier. But one thing seems to be broken when installing:

https://i.gyazo.com/07450ef85d0a048b347d48ca747255a3.png

How can I fix this?

**Comment by vintagedaddyo** [comment]
looks like a styling conflict with your existing theme that has existing font awesome forum icons in it. Removing existing  related styling before install and following the existing font awesome theme instructions in readme of reverting specified existing modified templates (unless you are confident with editing the customized templates of your theme and then follow those parts of instructions) should sort this out as this is something I have already pointed out with several users during the process of helping them with their support requests for their specific existing fa theme. Also note: if you are using "generic theme" by owlthemes,  note: most of those themes (all based on square by envy that was made into netpen by misharnet and then the rest of the themes are all modified variants of the netpen base so pretty much the edits would be mostly the same in every single pkg sold there give or take) from there use font awesome 4 not font awesome 5 and as I have pointed out for several users using those various themes (while yes I may have updated some of them fully to fa5 for specific user request the reality is the generic pkg you purchased is not using fa5) you would need to use the correct plugin for FA4: https://github.com/vintagedaddyo/MyBB_Plugin-MyFontAwesomeIconsFA4  unless you plan on manually updating the rest of the generic theme entirely to font awesome 5 library. Anyhoo if you are using the correct plugin and still have this issue and still need it resolved I can if I find the free time to do so dig in my files and have a look at my copy of the generic theme in reference to the fa4 plugin and specifically tell you what styling conflictions need to be removed. Lemme know.

Anyhoo as I don't currently have the free time to look at this for more than a few seconds here is just a real quick tip to get the fa4 version plugin to start playing well with that owlthemes generic theme

Example: https://ibb.co/fS7bKZp

global.css comment out:

```
/*
.forum_status {
    font-size: 15px !important;
    text-align: center;
}
.forum_status i {
	display: inline-block
}
.forum_on {
	color: #8d95a5;
}
.forum_off, .forum_offlock, .forum_offlink {
	color: #8d95a5;
}
.forum_off {
	opacity: .5;
}
.forum_on:before {
	font-family: 'FontAwesome';
	content: "\f07c"
}
.forum_off:before {
	font-family: 'FontAwesome';
	content: "\f07b"
}
.forum_offlock:before {
	font-family: 'FontAwesome';
	content: "\f023"
}
.forum_offlink:before {
	font-family: 'FontAwesome';
	content: "\f0c1"
}
*/

Also find in global.css and comment out:

/*
.bbp-forum a::before {
	font-family: 'FontAwesome';
	content: "\f07b";
	color: #5e646e;
	margin-right: 3px;
	margin-left: -5px;
}
*/
```


forumbit_depth2_cat:

```
<div class="row bottom-border">	
<div class="col-lg-1 text-center padding-8px"><div class="forum_status forum_{$lightbulb['folder']} ajax_mark_read" title="{$lightbulb['altonoff']}" id="mark_read_{$forum['fid']}"><i class="{$forum['myfontawesomeicon']}"></i></div></div>
	<div class="col-lg-5 padding-8px"><strong><a href="{$forum_url}">{$forum['name']}</a></strong>{$forum_viewers_text}<div class="small"><span class="help-block">{$forum['description']}</span>{$subforums}</div></div>
	<div class="col-lg-2 text-center small white-space-nowrap padding-8px">{$lang->forumbit_threads}:&nbsp;{$threads}{$unapproved['unapproved_threads']}<br>{$lang->forumbit_posts}:&nbsp;{$posts}{$unapproved['unapproved_posts']}</div>
	<div class="col-lg-4 text-center small white-space-nowrap padding-8px">{$lastpost}</div>
</div>
```

forumbit_depth2_forum:

```
<div class="row-bit bottom-border">	
<div class="tt col-lg-1 fstat no-padding padding-8px forum_status forum_{$lightbulb['folder']} ajax_mark_read" title="{$lightbulb['altonoff']}" id="mark_read_{$forum['fid']}"><i class="{$forum['myfontawesomeicon']}"></i></div>	
	<div class="col-lg-6 padding-top line-height-1">
	<strong><a href="{$forum_url}">{$forum['name']}</a></strong>
	{$forum_viewers_text}
	<div class="small padding-bottom-8px">
	<span class="help-block">{$forum['description']}<br />
	{$subforums}</span>
	{$modlist}
	</div>
	</div>
	<div class="col-lg-2 posts-bit text-center small white-space-nowrap padding-8px">{$lang->forumbit_threads}:&nbsp;{$threads}{$unapproved['unapproved_threads']}<br>{$lang->forumbit_posts}:&nbsp;{$posts}{$unapproved['unapproved_posts']}</div>
	<div class="col-lg-3 pull-right lastp small padding-8px white-space-nowrap text-right">{$lastpost}</div>
</div>
```



forumbit_depth3:


`<a href="{$forum_url}" title="{$forum_viewers_text_plain}">{$statusicon}&nbsp;{$forum['name']}</a>`


forumbit_depth3_statusicon:

`<div title="{$lightbulb['altonoff']}" class="subforumicon subforum_{$lightbulb['folder']} ajax_mark_read" id="mark_read_{$forum['fid']}"><i class="{$forum['myfontawesomeicon']}"></i></div>`



minor changes to attached myfontawesomeicons.css

```
.forum_status {/*background: none !important;height: 50px !important;width: 50px !important;font-size: 30px !important;*/ font-size: 15px !important; text-align: center !important;}
.forum_status i {display: inline-block !important;/*line-height: 50px !important;*/}
.forum_on {color: #009DFF !important;}
.forum_on i
.forum_off, .forum_offclose, .forum_offlink {color: #009DFF !important;}
.forum_off i {opacity: .4 !important;}
/*.forum_offclose i:before {content: "";}*/
/*.forum_offlink i:before {content: "";}*/
.subforumicon {/*background: none !important; height: 10px !important;width: 10px !important;display: inline-block !important;margin: 0 5px !important;*/ display: inline-block !important; color: #5e646e !important; margin-right: 3px !important; margin-left: -5px !important;}
.subforum_minion {color: #009DFF !important;}
.subforum_minioff, .subforum_minioffclose, .subforum_miniofflink {color: #009DFF !important;}
.subforum_minioff {opacity: .4 !important;}
/*.subforum_minioffclose i:before {content: "";}*/
/*.subforum_miniofflink i:before {content: "";}*/
.forum_legend, .forum_legend dt, .forum_legend dd {margin: 0 !important;padding: 0 !important;}
.forum_legend dd {float: left !important;margin-right: 10px !important;margin-top: 17px !important;}
.forum_legend dt {float: left !important;margin-right: 5px !important;}
```

And keep further editing and tweaking it from there for your usages, yeah sorry, due to my rather limited free time that lil quick tip is where I wish you best of luck
